'use strict';
(()=>{
const $=id=>document.getElementById(id);let page=0,pages=0,query='',version=0,controller=null,busy=false;const cache=new Map();const since=Math.floor(Date.now()/1000)-7*86400;
function safeURL(value){try{const u=new URL(value);return ['https:','http:'].includes(u.protocol)&&!u.username&&!u.password?u:null;}catch{return null;}}
function buttons(){ $('previous').disabled=busy||page===0;$('next').disabled=busy||page+1>=pages;$('search').disabled=busy;}
function show(body,retrieved){if(!Array.isArray(body.hits))throw Error('The news service returned an unexpected response.');pages=Number.isInteger(body.nbPages)?body.nbPages:0;$('stories').replaceChildren();let count=0;const seen=new Set();for(const item of body.hits){const url=safeURL(item.url);if(!url||typeof item.title!=='string'||!item.title.trim()||seen.has(url.href))continue;seen.add(url.href);count++;const article=document.createElement('article');article.className='story';const meta=document.createElement('div');meta.className='meta';const date=new Date(item.created_at);meta.textContent=url.hostname.replace(/^www\./,'')+' · Submitted '+(Number.isFinite(date.getTime())?date.toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'}):'date unavailable');const h=document.createElement('h3'),a=document.createElement('a');a.textContent=item.title;a.href=url.href;a.target='_blank';a.rel='noopener noreferrer';h.append(a);const read=document.createElement('a');read.className='read';read.textContent='Read original article ↗';read.href=url.href;read.target='_blank';read.rel='noopener noreferrer';article.append(meta,h,read);$('stories').append(article);}$('page').textContent=pages?'Page '+(page+1)+' of '+pages:'';$('notice').textContent=count?count+' stories · Retrieved '+new Date(retrieved).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):'No linked stories found on this page. Try another topic, search, or page.';}
async function load(){const n=++version;controller?.abort();const active=new AbortController();controller=active;busy=true;buttons();$('stories').replaceChildren();$('page').textContent='';$('notice').textContent='Loading stories…';$('heading').textContent=query?'Stories: '+query:'Latest stories';const endpoint=$('sort').value==='latest'?'search_by_date':'search';const params=new URLSearchParams({tags:'story',query,page:String(page),hitsPerPage:'15',numericFilters:'created_at_i>'+since});const key=endpoint+'?'+params;const timer=setTimeout(()=>active.abort(),20000);try{let entry=cache.get(key);if(!entry||Date.now()-entry.time>300000){const res=await fetch('https://hn.algolia.com/api/v1/'+key,{signal:active.signal});if(!res.ok)throw Error(res.status===429?'The news service is busy. Please try again shortly.':'News could not be loaded. Please try again.');entry={body:await res.json(),time:Date.now()};cache.set(key,entry);}if(n!==version)return;show(entry.body,entry.time);}catch(e){if(n===version){pages=0;$('notice').textContent=e.name==='AbortError'?'News loading timed out. Select Search news to retry.':e.message;}}finally{clearTimeout(timer);if(n===version){busy=false;buttons();}}}
$('search-form').onsubmit=e=>{e.preventDefault();query=$('query').value.trim();page=0;document.querySelectorAll('.topic').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.query===query)));load();};
document.querySelectorAll('.topic').forEach(b=>b.onclick=()=>{query=b.dataset.query;$('query').value=query;page=0;document.querySelectorAll('.topic').forEach(t=>t.setAttribute('aria-pressed',String(t===b)));load();});
$('sort').onchange=()=>{page=0;load();};$('previous').onclick=()=>{if(page>0){page--;load();}};$('next').onclick=()=>{if(page+1<pages){page++;load();}};load();
})();
