'use strict';
(()=>{
const $=id=>document.getElementById(id),store='raremotion.vault.v1';let key=null,salt=null,entries=[],raw=null,editing=null,busy=false,generation=0,timer=null;
const note=t=>$('notice').textContent=t;
function gate(){try{raw=localStorage.getItem(store);}catch{note('Browser storage is unavailable. The vault cannot be used here.');$('gate-fields').disabled=true;$('restore').disabled=true;return;}const exists=raw!==null;$('gate-title').textContent=exists?'Unlock your vault':'Create your vault';$('unlock').textContent=exists?'Unlock vault':'Create vault';$('create-fields').hidden=exists;$('confirm').required=!exists;$('restore-area').hidden=exists;}
function resetEditor(){editing=null;$('entry-form').reset();$('password').type='password';$('editor-title').textContent='Add a login';$('cancel').hidden=true;}
function touch(){clearTimeout(timer);if(key)timer=setTimeout(()=>lock('Vault locked after five minutes without activity.'),300000);}
function lock(message='Vault locked.'){generation++;key=null;salt=null;entries=[];busy=false;clearTimeout(timer);resetEditor();$('search').value='';$('entries').replaceChildren();$('master').value='';$('confirm').value='';$('workspace').hidden=true;$('gate').hidden=false;$('entry-fields').disabled=false;$('gate-fields').disabled=false;$('restore').disabled=false;gate();note(message);}
async function persist(next,k,s,expected,token){const envelope=JSON.stringify(await VaultCrypto.seal(next,k,s));if(token!==generation)throw Error('Vault locked before saving. Please unlock and try again.');if(!navigator.locks)throw Error('This browser cannot safely save this vault. Use a current browser.');await navigator.locks.request(store,()=>{if(token!==generation)throw Error('Vault locked before saving.');if(localStorage.getItem(store)!==expected)throw Error('Vault changed in another tab. Lock and unlock it before saving.');localStorage.setItem(store,envelope);});return envelope;}
function render(){const q=$('search').value.toLowerCase();$('entries').replaceChildren();let found=0;for(const item of entries){if(!(item.title+' '+item.username).toLowerCase().includes(q))continue;found++;const box=document.createElement('article');box.className='entry';const h=document.createElement('h3'),u=document.createElement('p'),actions=document.createElement('div');h.textContent=item.title;u.textContent=item.username||'No username';actions.className='actions';const edit=document.createElement('button'),copy=document.createElement('button'),remove=document.createElement('button');for(const b of [edit,copy,remove]){b.className='secondary';b.type='button';}edit.textContent='Edit';copy.textContent='Copy password';remove.textContent='Delete';edit.onclick=()=>{if(busy)return;editing=item.id;$('title').value=item.title;$('username').value=item.username;$('password').value=item.password;$('password').type='password';$('show').checked=false;$('editor-title').textContent='Edit login';$('cancel').hidden=false;$('title').focus();};copy.onclick=async()=>{try{await navigator.clipboard.writeText(item.password);note('Password copied to clipboard.');}catch{note('Clipboard access was blocked. Use Edit to view and copy the password.');}};remove.onclick=async()=>{if(busy||!confirm('Delete this saved login? This cannot be undone without a backup.'))return;await save(entries.filter(e=>e.id!==item.id),'Login deleted.');};actions.append(edit,copy,remove);box.append(h,u,actions);$('entries').append(box);}$('empty').hidden=found>0;$('empty').textContent=entries.length?'No matching logins.':'No logins yet. Add your first login.';}
async function save(next,message){if(busy||!key)return;busy=true;$('entry-fields').disabled=true;const token=generation;try{const updated=await persist(next,key,salt,raw,token);if(token!==generation)return;raw=updated;entries=next;resetEditor();render();note(message+' Download a fresh encrypted backup.');}catch(e){if(token===generation)note(e.message);}finally{if(token===generation){busy=false;$('entry-fields').disabled=false;}}}
$('unlock-form').onsubmit=async e=>{e.preventDefault();if(busy)return;const password=$('master').value,expected=raw,token=++generation;if(!raw&&(password.length<12||password!==$('confirm').value)){note('Use at least 12 characters and matching master passwords.');return;}busy=true;$('gate-fields').disabled=true;$('restore').disabled=true;note('Opening vault…');try{const env=raw?VaultCrypto.validate(JSON.parse(raw)):null;const s=env?env.salt:VaultCrypto.salt(),k=await VaultCrypto.key(password,s);const values=env?await VaultCrypto.open(env,k):[];let updated=expected;if(!env)updated=await persist(values,k,s,null,token);if(token!==generation)return;if(localStorage.getItem(store)!==updated)throw Error('Vault changed. Please try again.');key=k;salt=s;entries=values;raw=updated;$('master').value='';$('confirm').value='';$('gate').hidden=true;$('workspace').hidden=false;render();touch();note(env?'Vault unlocked.':'Vault created. Keep your master password and an encrypted backup.');}catch{if(token===generation)note('Could not open vault. Check the master password, browser storage, and backup integrity.');}finally{if(token===generation){busy=false;$('gate-fields').disabled=false;$('restore').disabled=false;}}};
$('entry-form').onsubmit=e=>{e.preventDefault();if(!key||busy)return;if(!editing&&entries.length>=200){note('This vault supports up to 200 logins.');return;}const value={id:editing||crypto.randomUUID(),title:$('title').value.trim(),username:$('username').value.trim(),password:$('password').value};if(!value.title){note('Enter an account name.');return;}save(editing?entries.map(x=>x.id===editing?value:x):[value,...entries],'Login saved.');};
$('show').onchange=()=>{$('password').type=$('show').checked?'text':'password';};$('cancel').onclick=resetEditor;$('search').oninput=render;$('lock').onclick=()=>lock();
$('backup').onclick=()=>{if(!raw||!key)return;const url=URL.createObjectURL(new Blob([raw],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='raremotion-vault-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);note('Encrypted backup download requested. It requires your master password to restore.');};
$('restore').onchange=async()=>{const file=$('restore').files[0];$('restore').value='';if(!file||busy)return;if(raw!==null||file.size>2000000){note('Restore needs an empty vault and a backup under 2 MB.');return;}const password=$('master').value;if(!password){note('Enter the backup’s master password, then choose the file again.');return;}const token=++generation;busy=true;$('gate-fields').disabled=true;$('restore').disabled=true;note('Checking encrypted backup…');try{const env=VaultCrypto.validate(JSON.parse(await file.text()));const k=await VaultCrypto.key(password,env.salt);await VaultCrypto.open(env,k);if(token!==generation)return;if(!navigator.locks)throw Error();await navigator.locks.request(store,()=>{if(token!==generation||localStorage.getItem(store)!==null)throw Error();localStorage.setItem(store,JSON.stringify(env));});if(token===generation)lock('Backup restored. Unlock with its master password.');}catch{if(token===generation)note('Restore failed. Check the file and master password. Your stored vault was not replaced.');}finally{if(token===generation){busy=false;$('gate-fields').disabled=false;$('restore').disabled=false;}}};
document.addEventListener('visibilitychange',()=>{if(document.hidden)lock();});window.addEventListener('pagehide',()=>lock());window.addEventListener('storage',e=>{if(e.key===store)lock('Vault changed in another tab. Unlock to reload it.');});for(const event of ['pointerdown','keydown'])document.addEventListener(event,touch,{passive:true});
if(!crypto.subtle||!navigator.locks){$('gate-fields').disabled=true;$('restore').disabled=true;note('Use a current browser over HTTPS to use this vault.');}else gate();
})();
