'use strict';
(()=>{
const $=id=>document.getElementById(id);let data=null,selected='',version=0,controller=null;const cache=new Map();
const fmt=(v,s='')=>Number.isFinite(v)?Math.round(v*10)/10+s:'Unavailable';
const temp=v=>fmt(Number.isFinite(v)?($('unit').value==='f'?v*9/5+32:v):null,$('unit').value==='f'?'°F':'°C');
const label=s=>(s||'Forecast unavailable').replace(/_(day|night|polartwilight)$/,'').replace(/([a-z])([A-Z])/g,'$1 $2').replace(/_/g,' ').replace(/clearsky/,'Clear sky').replace(/fair/,'Fair').replace(/partlycloudy/,'Partly cloudy').replace(/cloudy/,'Cloudy').replace(/lightrain/,'Light rain').replace(/heavyrain/,'Heavy rain').replace(/rainshowers/,'Rain showers').replace(/andthunder/,' and thunder');
async function get(url,signal){const r=await fetch(url,{signal});if(!r.ok)throw Error(r.status===429?'The weather service is busy. Please try again later.':'Unable to load data. Please try again.');return r.json();}
function render(){if(!data)return;const now=Date.now();const all=data.properties.timeseries;const rows=all.filter(r=>new Date(r.time).getTime()>=now-3600000);if(!rows.length)throw Error('This forecast is out of date. Please try again later.');const first=rows[0],d=first.data.instant.details;$('place').textContent=selected;$('temperature').textContent=temp(d.air_temperature);$('condition').textContent=label(first.data.next_1_hours?.summary?.symbol_code||first.data.next_6_hours?.summary?.symbol_code);$('humidity').textContent=fmt(d.relative_humidity,'%');$('wind').textContent=fmt(Number.isFinite(d.wind_speed)?d.wind_speed*3.6:null,' km/h');$('rain').textContent=fmt(first.data.next_1_hours?.details?.precipitation_amount,' mm');$('updated').textContent='Forecast for '+new Date(first.time).toLocaleString('en-GB',{timeZone:'UTC'})+' UTC · Model updated '+new Date(data.properties.meta.updated_at).toLocaleString('en-GB',{timeZone:'UTC'})+' UTC';$('forecast').replaceChildren();
const start=new Date(first.time).getTime();let last=-Infinity;rows.filter(r=>new Date(r.time).getTime()<start+86400000).forEach(r=>{const t=new Date(r.time).getTime();if(t-last<10800000)return;last=t;const box=document.createElement('div');box.className='hour';const time=document.createElement('small'),v=document.createElement('strong'),desc=document.createElement('span');time.textContent=new Date(r.time).toLocaleString('en-GB',{timeZone:'UTC',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'});v.textContent=temp(r.data.instant.details.air_temperature);desc.textContent=label(r.data.next_1_hours?.summary?.symbol_code||r.data.next_6_hours?.summary?.symbol_code);box.append(time,v,desc);$('forecast').append(box);});$('weather').hidden=false;$('empty').hidden=true;}
async function choose(feature){const n=++version;controller?.abort();controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),20000);data=null;$('weather').hidden=true;$('empty').hidden=true;selected=[feature.properties.name,feature.properties.state,feature.properties.country].filter(Boolean).join(', ');$('place').textContent=selected;$('notice').textContent='Loading forecast…';try{const [lon,lat]=feature.geometry.coordinates;if(!Number.isFinite(lat)||!Number.isFinite(lon))throw Error('This place has no valid coordinates.');const q=new URLSearchParams({lat:lat.toFixed(4),lon:lon.toFixed(4)});const key=q.toString();let saved=cache.get(key);if(!saved||saved.until<Date.now()){const r=await fetch('https://api.met.no/weatherapi/locationforecast/2.0/compact?'+q,{signal:controller.signal});if(!r.ok)throw Error(r.status===429?'Weather service is busy. Please try later.':'Forecast unavailable. Please try another place or try again later.');const body=await r.json();if(!Array.isArray(body.properties?.timeseries)||!body.properties.timeseries.length)throw Error('No forecast is available for this place.');saved={body,until:Math.max(Date.now()+600000,Date.parse(r.headers.get('expires'))||0)};cache.set(key,saved);}if(n!==version)return;data=saved.body;render();$('notice').textContent='Forecast loaded.';}catch(e){if(n===version){$('notice').textContent=e.name==='AbortError'?'The request timed out. Select a place to retry.':e.message;$('empty').hidden=false;}}finally{clearTimeout(timeout);}}
$('search-form').onsubmit=async e=>{e.preventDefault();const q=$('search').value.trim();if(q.length<2)return;const n=++version;controller?.abort();controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),15000);$('results').replaceChildren();$('find').disabled=true;$('notice').textContent='Finding places…';try{const body=await get('https://photon.komoot.io/api/?'+new URLSearchParams({q,limit:'5',lang:'en'}),controller.signal);if(n!==version)return;const features=(body.features||[]).filter(f=>f.geometry?.type==='Point');$('notice').textContent=features.length?'Choose your place below.':'No matching places. Try a nearby city or add the country.';features.forEach(f=>{const b=document.createElement('button');b.type='button';b.className='secondary result';b.textContent=[f.properties.name,f.properties.state,f.properties.country].filter(Boolean).join(', ');b.onclick=()=>choose(f);$('results').append(b);});}catch(e){if(n===version)$('notice').textContent=e.name==='AbortError'?'Search timed out. Please try again.':e.message;}finally{clearTimeout(timeout);$('find').disabled=false;}};
$('unit').onchange=()=>{if(data)render();};
})();
